on:
  schedule:
    - cron:  "*/10 * * *"

jobs:
  run-r-script:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v3
      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - name: Execute Script
        run: |
          Rscript "R/get_daily_energieerzeugung.R"

      - name: Commit results
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add .
          git commit -m "new data" || echo "No changes to commit"
          git push origin || echo "No changes to commit"
