# Hourly scraping
name: test curl

# Controls when the action will run.
on:
  schedule:
    - cron:  "0 1 * * *"
  workflow_dispatch:

jobs:
  autoscrape:

    # The type of runner that the job will run on
    runs-on: macos-latest

    steps:
      - shell: bash
        run: |
          curl https://transparency.apg.at/transparency-api/api/v1/Download/AGPT/German/M15/2022-08-01T000000/2022-09-01T000000 > test.json
          cat test.json


